### ISSUE TITLE
Support for Prometheus Service definition

### ISSUE THREAD

**Issue by centromere** [nginxinc/kubernetes-ingress#3129] opened 2022-10-04 16:17 UTC
**Is your feature request related to a problem? Please describe.**
https://github.com/nginxinc/kubernetes-ingress/issues/889 implements a ServiceMonitor resource, [but it does not provide the underlying Service resource](https://github.com/nginxinc/kubernetes-ingress/issues/889#issuecomment-1194581232).

(h/t @hostalp)

**Describe the solution you'd like**
An optional Service resource to be installed alongside the ServiceMonitor.

**Describe alternatives you've considered**
Creating the Service resource by hand.

**Comment by AaronShiels** [comment] 2022-11-29 23:25
I'd be inclined to upgrade this to a bug, as this looks like an oversight on intended functionality.

The chart supports the ability to decorate the _pods_ with `prometheus.io/scrape: "true"` while also offering a ServiceMonitor, so I'd say the author clearly intended these two to marry up. The problem is that the ServiceMonitor should be a PodMonitor to scrape the pods *or* a separate service for scraping metrics would be provisioned with the Prometheus annotations in place of the pod annotations.

**Comment by coolbry95** [comment] 2022-11-30 15:53
Does it need to be a separate service? I thought it just needs the port exposed?

**Comment by centromere** [comment] 2022-11-30 16:31
> Does it need to be a separate service? I thought it just needs the port exposed?

ServiceMonitors monitor Services, PodMonitors monitor Pods. If there is no Service, it is fruitless to deploy a ServiceMonitor.

**Comment by coolbry95** [comment] 2022-11-30 16:42
There is the nginx service though. The PR adds the prometheus port to it.

Can you link to the documentation where it says it needs its own service?

**Comment by coolbry95** [comment] 2022-11-30 19:41
I can confirm my PR should work. We are running multiple applications that all have a ServiceMonitor and a single Service that metrics are scraped from.

The port can be renamed to metrics.

**Comment by brianehlert** [comment] 2022-11-30 20:14
I am wondering if the perception here is a technical one.
The NGINX Ingress Controller implementation is that the Control component runs alongside the data plane - within the same pod.  It is this Controller that presents the Prometheus endpoint. 
The metrics from individual pods are technically discrete.

I guess the question is if this splits hairs, or if it is a necessary change because something is not represented correctly or is broken.

And then what needs to happen if we separate the controller from the data plane....  If the Control Plane is then represented as the NIC service, rather than individual pod endpoints.

**Comment by AaronShiels** [comment] 2022-11-30 20:21
My understanding of scraping the pods vs scaping a service for ServiceMonitors is that they give effectively the same end result, bar some edge cases covered in [this comment thread](https://groups.google.com/g/prometheus-users/c/jDEzVHUUFzw). But for this to work, I think we just need to choose scraping pods + PodMonitor or scraping service + ServiceMonitor, as @centromere alluded to. Currently they are simply mismatched.

@coolbry95 I'm not sure your change will work, as I believe the service needs to be explicitly of type ClusterIP (the default), while the primary Nginx Ingress service is generally of type LoadBalancer. The ServiceMonitor uses the service to query the cluster IP of the pods behind the service in order to work out what to scrape, so we need to ensure that functionality still works regardless of service type.

**Comment by coolbry95** [comment] 2022-11-30 21:29
@AaronShiels The service type issue makes sense. I will update my PR to add a new service for metrics.

**Comment by brianehlert** [comment] 2023-07-11 14:58
Anyone able to help me understand the current situation on this?
I see the linked PR was closed and not merged.

From the conversation on both sides I see:

- There is a desire for an additional Service for Prometheus
- This should be ClusterIP (not exposed as part of the primary ingress controller service which is loadbalancer)

Did I miss a concern?

**Comment by hostalp** [comment] 2023-07-11 15:45
It appears that the linked PR appears to be just a quick and simple solution, so a better (configurable via values) approach may be worth considering.

The whole point is that PR #2831 solves only a half of the problem, therefore the result isn't fully usable. It adds the ServiceMonitor resource, but not the Service resource (for the endpoint that publishes the metrics) to which the ServiceMonitor should refer.

See my simple example at https://github.com/nginxinc/kubernetes-ingress/issues/889#issuecomment-1084569000 for how the end result should look like at minimum. This is what we add manually (with some additional optional settings such as interval and scrapeTimeout) and only then it really works.

**Comment by brianehlert** [comment] 2023-07-19 14:22
Thank you all for your input on this issue.  I admit I am not a Prometheus expert and want to make sure the right thing goes into the product.

@hostalp your comment "The whole point is that PR https://github.com/nginxinc/kubernetes-ingress/pull/2831 solves only a half of the problem, therefore the result isn't fully usable." has only become clear to me recently.

My concern is that in the end, Prometheus collects from all of the ingress controller pods as this is what is necessary for accurate data.  Which is critically important.  @AaronShiels  your comment here: "My understanding of scraping the pods vs scaping a service for ServiceMonitors is that they give effectively the same end result, bar some edge cases covered in [this comment thread](https://groups.google.com/g/prometheus-users/c/jDEzVHUUFzw)." really helped with that groups link that really asks the exact same questions that were rolling around in my head about this.

And just to finish pulling the pieces together: what @hostalp posts here: https://github.com/nginxinc/kubernetes-ingress/issues/889#issuecomment-1084569000 is what should be in the Helm chart and as a result is what the Operator should in turn also be outputting (since we derive our Operator from our Helm chart)

Given all that, and that the original PR proposed by @coolbry95 has been closed after it was determined it did not meet the mark.  
Is there anyone on thread that is willing / able to submit the enhancement to the Helm chart to define both an additional ClusterIP service definition for Prometheus (when the endpoint flag is true) as well as the ServiceMonitor for Prometheus?

**Comment by brianehlert** [comment] 2023-08-09 22:33
Please take a look over here as we plan to resolve this: https://github.com/nginxinc/kubernetes-ingress/issues/4210 and give us some feedback.

**Comment by vepatel** [comment] 2023-12-05 08:50
closing as resolved in https://github.com/nginxinc/kubernetes-ingress/issues/4210

**Closed by vepatel** 2023-12-05 08:50 UTC
Labels: proposal, backlog, help wanted
