### ISSUE TITLE
Generated config wraps directives on one line, not properly formatted .conf

### ISSUE THREAD

**Issue by jasonwilliams14** [nginxinc/kubernetes-ingress#5056] opened 2024-02-08 23:49 UTC
Description:

Moving from 3.x to 3.4.2, the generated .conf has wrapping configs with the directives inside the comments.
An example:

The new conf in 3.4.2:
```
set $resource_namespace "default";# geoip headersproxy_set_header X-GEOIP-COUNTRY "$geoip2_data_country_code";proxy_set_header X-GEOIP-CITY "$geoip2_data_city_name";# uri rewriteproxy_set_header x-original-prefix /;rewrite "^/coffeel(/.*)$" $1 break;# cacheproxy_cache [cache_path(http://<path>);proxy_cache_valid 200     120m;proxy_cache_valid any     1s;proxy_cache_lock on;proxy_cache_min_uses 1;proxy_cache_revalidate on;proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;proxy_cache_background_update on;#proxy_hide_header Cache-Control;add_header Last-Modified $upstream_http_date;# add security headersadd_header 'X-Content-Type-Options' 'nosniff';add_header 'Referrer-Policy' 'strict-origin-when-cross-origin';
```
The same .conf generated in 3.x:

```
location ~ "^/coffee/" {
        set $service "coffee";
        set $resource_type "virtualserverroute";
        set $resource_name "coffee";
        set $resource_namespace "coffee";
        # geoip headers
        proxy_set_header X-GEOIP-COUNTRY "$geoip2_data_country_code";
        proxy_set_header X-GEOIP-CITY "$geoip2_data_city_name";
        # uri rewrite
        proxy_set_header x-original-prefix /;
        rewrite "^/coffee(/.*)$" $1 break;
        # cache
        proxy_cache [coffee-cache](http://coffee);
        proxy_cache_valid 200     120m;
        proxy_cache_valid any     1s;
        proxy_cache_lock on;
        proxy_cache_min_uses 1;
        proxy_cache_revalidate on;
        proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
        #proxy_hide_header Cache-Control;
        add_header Last-Modified $upstream_http_date;
        # add security headers
        add_header 'X-Content-Type-Options' 'nosniff';
        add_header 'Referrer-Policy' 'strict-origin-when-cross-origin';
```
To reproduce the issue:

I tested on 3.1.1, then on 3.4.0 to 3.4.2.
3.1.1 generated the .conf correctly, as the second item above.
The 3.4.x releases generated all the directives on the same line above.

Environment:
Kind, K3d and AKS

Tested versions:
3.1.1, 3.2, 3.3 and 3.4.0, 3.4.1 and 3.4.2

The problem only occurs on the 3.4.x release.

Possible related issues:

https://github.com/nginxinc/kubernetes-ingress/issues/4824
https://github.com/nginxinc/kubernetes-ingress/pull/5020

**Comment by vepatel** [comment] 2024-02-09 11:46
@jasonwilliams14 looks like a duplicate of https://github.com/nginxinc/kubernetes-ingress/issues/4824

**Comment by j1m-ryan** [comment] 2024-02-09 14:23
The fix for this bug is now cherry picked into `release-3.4`, so will appear in `3.4.3`

**Comment by jasonwilliams14** [comment] 2024-02-09 15:10
> @jasonwilliams14 looks like a duplicate of #4824

yep, linked to it in the description.

**Closed** 2024-02-12 15:38 UTC
Labels: bug, backlog
