### ISSUE TITLE
Nginx-ingress pod installed with "CrashLoopBackOff" status.   

### ISSUE THREAD

**Issue by yujiannj** [nginxinc/kubernetes-ingress#911] opened 2020-04-05 12:00 UTC
I followed few installation guides found from the internet and try to install Nginx Ingress Controller
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/  

The error as below:
1 main.go:169] Starting NGINX Ingress controller Version=1.6.3 GitCommit=b9378d56
1 main.go:275] Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get https://10.96.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret: dial tcp 10.96.0.1:443: i/o timeout

My kubernetes version is v.1.18.0 on Ubuntu 18.04
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:56:30Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

I have installed few times but ended up with the same error. 

Really appreciate if you could help me on this.
Thanks in advance !

**Comment by Rulox** [comment] 2020-04-06 08:57
Hi @yujiannj 

It seems the Ingress Controller can't find the Default Server Secret. Let's try to debug your problem.

In the docs, one of the steps of the installation is the deployment of this secret. In this [step](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/#create-the-default-secret-customization-configmap-and-custom-resource-definitions) you should have deployed the secret using this command:

```bash
$ kubectl apply -f common/default-server-secret.yaml
```

In order to check if this is done correctly, could let me know the results of this command?:
```bash
$ kubectl get secret -n nginx-ingress default-server-secret
```

After checking this I'll help you to troubleshoot the issue if this is not the problem.

Thanks

**Comment by yujiannj** [comment] 2020-04-06 13:22
Hi Rulox,

Thanks for your prompt reply.

Please find the results below:
yujian@kubemaster:~$ kubectl get secret -n nginx-ingress default-server-secret
NAME                    TYPE     DATA   AGE
default-server-secret   Opaque   2      26h

Thanks a lot!

**Comment by Rulox** [comment] 2020-04-06 13:31
Hey @yujiannj thanks.

Could you possibly set the Ingress Controller verbosity to level 3 and show us the logs? 
In order to set the Ingress Controller, set the `-v` command argument to 3. More info on the CLI arguments can be found [here](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/).

In the meantime I'll try to reproduce this, maybe it's a problem with the Kubernetes version, I think 18 is pretty new, I'll double check this.

PS: Another problem can be that somehow the pod can't access the k8s API, I am seeing the error is a timeout. Do you have any firewall or networking configuration that could prevent the Ingress Controller pod to access the k8s API?

Thanks and sorry for the inconvenience.

**Comment by yujiannj** [comment] 2020-04-06 14:51
Hi Rulox,

I am quite new to the Ingress Controller. Not sure if i have done it correctly ? 

I have edited the deployment of ingress controller and added -v=3 to "args" and restarted the deploymemt by rollout command:

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-ingress","namespace":"nginx-ingress"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx-ingress"}},"template":{"metadata":{"labels":{"app":"nginx-ingress"}},"spec":{"containers":[{"args":["-nginx-configmaps=$(POD_NAMESPACE)/nginx-config","**-v=3**","-default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}],"image":"nginx/nginx-ingress:1.6.3","name":"nginx-ingress","ports":[{"containerPort":80,"name":"http"},{"containerPort":443,"name":"https"}],"securityContext":{"allowPrivilegeEscalation":true,"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"runAsUser":101}}],"serviceAccountName":"nginx-ingress"}}}}
  creationTimestamp: "2020-04-05T19:06:42Z"
  generation: 3
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:

However, when i described the deployment,  i didn't find the v=3 there . 
yujian@kubemaster:~$ kubectl describe deployment -n nginx-ingress nginx-ingress
Name:                   nginx-ingress
Namespace:              nginx-ingress
CreationTimestamp:      Sun, 05 Apr 2020 19:06:42 +0000
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 2
Selector:               app=nginx-ingress
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=nginx-ingress
  Annotations:      kubectl.kubernetes.io/restartedAt: 2020-04-06T22:39:39Z
  Service Account:  nginx-ingress
  Containers:
   nginx-ingress:
    Image:       nginx/nginx-ingress:1.6.3
    Ports:       80/TCP, 443/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
      -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
    Environment:
      POD_NAMESPACE:   (v1:metadata.namespace)
      POD_NAME:        (v1:metadata.name)
    Mounts:           <none>
  Volumes:            <none>

The log that i have extracted are the same as previous one. 
yujian@kubemaster:~$ kubectl logs  -n nginx-ingress nginx-ingress-598f45754c-5mfwv
I0406 22:48:49.723338       1 main.go:169] Starting NGINX Ingress controller Version=1.6.3 GitCommit=b9378d56
F0406 22:49:19.727092       1 main.go:275] Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get https://10.96.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret: dial tcp 10.96.0.1:443: i/o timeout

Need your advice on this .  Thanks.

**Comment by yujiannj** [comment] 2020-04-06 15:03
Hi Rulox,

I have managed to add in the -v=3

yujian@kubemaster:~/ingress/kubernetes-ingress/deployments$ kubectl describe deployment -n nginx-ingress nginx-ingress
Name:                   nginx-ingress
Namespace:              nginx-ingress
CreationTimestamp:      Sun, 05 Apr 2020 19:06:42 +0000
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 3
Selector:               app=nginx-ingress
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=nginx-ingress
  Annotations:      kubectl.kubernetes.io/restartedAt: 2020-04-06T22:39:39Z
  Service Account:  nginx-ingress
  Containers:
   nginx-ingress:
    Image:       nginx/nginx-ingress:1.6.3
    Ports:       80/TCP, 443/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
      -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
      -v=3
    Environment:
      POD_NAMESPACE:   (v1:metadata.namespace)
      POD_NAME:        (v1:metadata.name)
    Mounts:           <none>
  Volumes:            <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      False   MinimumReplicasUnavailable
OldReplicaSets:  <none>
NewReplicaSet:   nginx-ingress-68cc64dc9d (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  20m   deployment-controller  Scaled up replica set nginx-ingress-598f45754c to 1
  Normal  ScalingReplicaSet  20m   deployment-controller  Scaled down replica set nginx-ingress-7cd9549876 to 0
  Normal  ScalingReplicaSet  2m5s  deployment-controller  Scaled up replica set nginx-ingress-68cc64dc9d to 1
  Normal  ScalingReplicaSet  2m3s  deployment-controller  Scaled down replica set nginx-ingress-598f45754c to 0

However the log remain the same
yujian@kubemaster:~/ingress/kubernetes-ingress/deployments$ kubectl logs --namespace=nginx-ingress nginx-ingress-68cc64dc9d-78b6g
I0406 23:01:20.182875       1 main.go:169] Starting NGINX Ingress controller Version=1.6.3 GitCommit=b9378d56
F0406 23:01:50.186273       1 main.go:275] Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get https://10.96.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret: dial tcp 10.96.0.1:443: i/o timeout

Thanks

**Comment by Rulox** [comment] 2020-04-07 11:00
This is interesting.

So the problem here is that the Ingress Controller timeouts when trying to get the default sever secret from the k8s API as I said. I've tested this version of the Ingress Controller and it's working on my end for Kubernetes 1.18.

This seems to be some kind of connection problem in the network (either from the pod or the ubuntu machine you have).

Could yo try to access the Kubernetes API manually from inside the Ingress Controller pod?, the steps would be:

1. Edit the Deployment or Daemonset to add a new container in the Ingress Controller pod (this is because Ingress Controller pod does not allow `root` so we can't install tools like `curl`). For example `alpine`.
```yaml
- image: alpine
  imagePullPolicy: Always
  name: alpine
  command: ["sh", "-c", "while true; do sleep 30; done"]
```
2. Enter in the alpine container and save the token for the k8s API in a variable:
```
$ KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
```
3. Now use `curl` (you can install it if necessary with `apk add curl`) to try to get the same default-secret the Ingress Controller is having issues with:
```
$ curl -H "Authorization: Bearer $KUBE_TOKEN" https://kubernetes.default.svc:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret --insecure
```

If you get the secret let me know. If you see a timeout or an error, it's most likely a problem in your Kubernetes installation or your machine.

Let me know if this helped

**Comment by yujiannj** [comment] 2020-04-08 12:39
Hi Rulox,

I managed to add a container in the ingress controller pod. 
But there is no bash for me to enter the container. Not sure how to set KUBE_TOKEN. 
 
yujian@kubemaster:~/ingress/kubernetes-ingress/deployments$ kubectl exec -t -i -n nginx-ingress nginx-ingress-8447d77bfb-4czl4 -c alpine bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
command terminated with exit code 126


yujian@kubemaster:~/ingress/kubernetes-ingress/deployments$ kubectl exec -t -i -n nginx-ingress nginx-ingress-8447d77bfb-4czl4 -c alpine ls /bin
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
arch           echo           kill           netstat        sh
ash            ed             link           nice           sleep
base64         egrep          linux32        pidof          stat
bbconfig       false          linux64        ping           stty
busybox        fatattr        ln             ping6          su
cat            fdflush        login          pipe_progress  sync
chgrp          fgrep          ls             printenv       tar
chmod          fsync          lzop           ps             touch
chown          getopt         makemime       pwd            true
conspy         grep           mkdir          reformime      umount
cp             gunzip         mknod          rev            uname
date           gzip           mktemp         rm             usleep
dd             hostname       more           rmdir          watch
df             ionice         mount          run-parts      zcat
dmesg          iostat         mountpoint     sed
dnsdomainname  ipcalc         mpstat         setpriv
dumpkmap       kbd_mode       mv             setserial

Thanks a lot.

**Comment by mohit5577** [comment] 2020-04-08 13:10
HI Rulox,

I am also facing the same issue. In my case there is one master and 2 worker nodes. The IC pod on master is working fine but on the worker node it is failing. More details can be found in the link.
https://github.com/nginxinc/kubernetes-ingress/issues/912#issue-595938198

-Regards
  Mohit

**Comment by mohit5577** [comment] 2020-04-08 13:24
Also in the tiller pod i am getting the following error 

[causer@master deployments]$ kubectl logs tiller-deploy-754f98dbfc-f7ztt -n kube-system
[main] 2020/04/07 13:19:03 Starting Tiller v2.16.5 (tls=false)
[main] 2020/04/07 13:19:03 GRPC listening on :44134
[main] 2020/04/07 13:19:03 Probes listening on :44135
[main] 2020/04/07 13:19:03 Storage driver is ConfigMap
[main] 2020/04/07 13:19:03 Max history per release is 0
[storage] 2020/04/07 14:41:53 listing all releases with filter
[storage/driver] 2020/04/07 14:42:23 list: failed to list: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: i/o timeout

**Comment by Rulox** [comment] 2020-04-08 13:26
@yujiannj I think alpine doesn't have bash, I believe is `sh`:

```
$  kubectl exec -t -i -n nginx-ingress nginx-ingress-8447d77bfb-4czl4 -c alpine sh
```


@mohit5577 That suggests a problem in your environment or calico configuration. If the tiller pod can't access the API I am afraid there's nothing we can do and it's a networking problem on your end. Maybe Calico support can help you out there?. 

As my colleague said in this comment https://github.com/nginxinc/kubernetes-ingress/issues/912#issuecomment-610600417 the IC must be able to connect to the k8s API to work.

**Comment by yujiannj** [comment] 2020-04-08 13:40
Hi Rulox ,

One more error during the installation of curl in container 

/ # apk add curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]

Thanks

**Comment by Rulox** [comment] 2020-04-08 13:44
Hi @yujiannj I am afraid I can't help you with this, I offered a way to help with your networking problem but this is not a problem of the Ingress Controller. I suggest you maybe try other channels of support (maybe kubernetes slack or Github?) 

It seems this is a problem in your network/environment, nothing to do with our Ingress Controller. Sorry

**Comment by yujiannj** [comment] 2020-04-08 13:55
Hi Rulox,

Ok. Anyway, thanks for your help ! 

Yujian

**Comment by mohit5577** [comment] 2020-04-08 14:28
> @yujiannj I think alpine doesn't have bash, I believe is `sh`:
> 
> ```
> $  kubectl exec -t -i -n nginx-ingress nginx-ingress-8447d77bfb-4czl4 -c alpine sh
> ```
> 
> @mohit5577 That suggests a problem in your environment or calico configuration. If the tiller pod can't access the API I am afraid there's nothing we can do and it's a networking problem on your end. Maybe Calico support can help you out there?.
> 
> As my colleague said in this comment [#912 (comment)](https://github.com/nginxinc/kubernetes-ingress/issues/912#issuecomment-610600417) the IC must be able to connect to the k8s API to work.

Thanks Rulox . I will contact Calico support.

-Regards
  Mohit

**Comment by Rulox** [comment] 2020-04-09 09:39
Thanks, closing this. If any of you have other problems feel free too open another issue.

**Closed by Rulox** 2020-04-09 09:39 UTC

**Comment by rakeshv12** [comment] 2020-11-25 18:33
HI Team,
Could any help me to resolve the below, As i am struggling since 2 weeks.
# kubectl get all -n nginx-ingress
NAME                      READY   STATUS    RESTARTS   AGE
pod/nginx-ingress-b9wdk   0/1     Running   2          92s
pod/nginx-ingress-njdhg   0/1     Error     4          92s

Environment details:
version details of K8 components:
# kubectl version --short
Client Version: v1.18.0
Server Version: v1.18.0
# kube-apiserver --version
Kubernetes v1.18.0
root@master2:~# kube-controller-manager --version
Kubernetes v1.18.0
root@master2:~# kube-scheduler --version
I1125 18:27:49.481905   11198 registry.go:150] Registering EvenPodsSpread predicate and priority function
I1125 18:27:49.482062   11198 registry.go:150] Registering EvenPodsSpread predicate and priority function
Kubernetes v1.18.0

weave net is using internal pod communication.
-------------------------
virtual machins:-
2 K8 masters node
2 K8 workers nodes
1 LB 

Nginx-controller installation fallow link:-
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/

# kubectl apply -f common/ns-and-sa.yaml
namespace/nginx-ingress created
serviceaccount/nginx-ingress created


# kubectl apply -f rbac/rbac.yaml
clusterrole.rbac.authorization.k8s.io/nginx-ingress created
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress created


# kubectl apply -f rbac/ap-rbac.yaml
clusterrole.rbac.authorization.k8s.io/nginx-ingress-app-protect unchanged
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-app-protect unchanged

# kubectl apply -f common/default-server-secret.yaml
secret/default-server-secret created

# kubectl apply -f common/nginx-config.yaml
configmap/nginx-config created

# kubectl apply -f daemon-set/nginx-ingress.yaml
daemonset.apps/nginx-ingress created


After all thins i did still my nginx-controller pods didn't come up. would any one help here.

Thanks
