### ISSUE TITLE
Ingress forwards traffic to the wrong ips under certain situations when a pod gets re created

### ISSUE THREAD

**Issue by bilby91** [nginxinc/kubernetes-ingress#622] opened 2019-07-16 00:41 UTC
Hello,

I'm writing this issue as a bug but I'm not 100% sure if this a bug in the `kubernetes-ingress` so please let me know if anyone thinks this is not appropriate. 

We've been experiencing the issue described on #448 for some time, under certain conditions, our ingress failed to forward traffic to the pods under a given service, even if the pods were up and in ready state. Hitting the service using kube-proxy worked perfectly fine while the ingress was not able to route the traffic property. 

After a lot of investigation, we were able to build an environment in our system that would reproduce the problem. We were able to reproduce the problem if we did the following:

1) Deploy a new image of our app
2) Change the resource requests from `1000m` to `1001m` and let the `nginx-ingress` reconfigure itself for the new pods that were going to be created.

After doing that (on an already deployed image), the ingress started to fail. After more investigation we realized that we had two deployments that had the same selectors than the deployment that actually handles the service traffic, so, we had two pods that matched the selector but didn't expose the appropriate ports. When deploying a new image for the first time, this doesn't seem to cause an issue for `nginx-ingress` , now, if we did a modification (like the resources requests change), we could see an error in the `nginx-ingress` logs that would say:

```
W0715 22:39:18.705092       1 controller.go:993] Error retrieving endpoints for the service my-app: Error determining target port for port {1 0 web} in Ingress: Error finding named port &ServicePort{Name:web,Protocol:TCP,Port:80,TargetPort:unicorn,NodePort:0,} in pod my-wrong-pod-5b969674c9-jh8vl: no suitable port for manifest: 173129d3-a750-11e9-8333-12e0f4202016
```

The other strange thing about this issue is that, if we change back from `1001m` to `1000m` again, `nginx-ingress` was able to route traffic perfectly fine again. 
 
**Expected behavior**
Again, I'm not sure if this is a bug or not but I would expect to see the error message in the description on every deployment, not sure why this only happen under this context.

**Your environment**
* Version of the Ingress Controller:  `nginx/nginx-ingress:1.4.5-alpine`
* Version of Kubernetes: 1.11
* Kubernetes platform: EKS
* Using NGINX or NGINX Plus: NGINX

**Comment by Dean-Coakley** [comment] 2019-07-16 12:41
Hi @bilby91 

Thanks for reporting this issue you're having. The included details about environment and logs are helpful.

Can you clarify what you mean by?:
> Change the resource requests from 1000m to 1001m and let the nginx-ingress reconfigure itself for the new pods that were going to be created.

Can you please include how you performed this change?

**Comment by bilby91** [comment] 2019-07-16 15:36
Hello @Dean-Coakley !

What I mean with that is that we modify an already running k8 deployment by just changing one of the containers resources cpu requests. Those values are the values we modified. Would that make sense ?

The change was performed with using helm. I'm pretty sure we were able to reproduce the problem by just editing the deployment directly using `kubectl edit deployment XX`

Let me know if I can provide any further information.

**Comment by Dean-Coakley** [comment] 2019-07-17 18:53
Hi @bilby91 

I haven't been able to repro this issue with similar results yet.

It would be great if you could share the output of `kubectl get endpoints`, `kubectl get pods` and `kubectl describe ingress`. Or if you could share some of any manifests that repro this issue, so I can better understand your use case.

> The change was performed with using helm. I'm pretty sure we were able to reproduce the problem by just editing the deployment directly using kubectl edit deployment XX

To my knowledge this is not possible with our helm chart. Have you made extensions to our chart, or are you using your own implementation?

**Comment by bilby91** [comment] 2019-07-17 23:06
Hey @Dean-Coakley !!

I'm pasting the requested information from the production environment which still has the problem (we are just not making any of the changes that we know break the ingress).

```
AWS_PROFILE=production kubectl get endpoints -n my-app
NAME                         ENDPOINTS                                                      AGE
my-app              10.6.28.127:3000,10.6.33.78:3000,10.6.8.149:3000 + 1 more...   4d
```

```
AWS_PROFILE=production kubectl get ingresses -n my-app
NAME                         HOSTS                                ADDRESS   PORTS     AGE
my-app              app.my-company.com                               80        4d
```

I'm not sending get pods since they are a lot of them and most of them are not related. All of the pods were running fine with no Warning/Error messages.

> To my knowledge this is not possible with our helm chart. Have you made extensions to our chart, or are you using your own implementation?

That is very true. We use the `helm-edit` plugin to perform those kind of changes.

**Comment by Dean-Coakley** [comment] 2019-07-19 14:53
@bilby91 Thanks for the additional details.

I was able to reproduce your issue!

The issue seems to arise when using a named port. Perhaps using a port number could be a workaround. Would that work for your use case?

> Change the resource requests from 1000m to 1001m and let the nginx-ingress reconfigure itself for the new pods that were going to be created.

I was able to reproduce the error without performing this edit. This appeared to be unrelated.


Why for your use case is having two deployments with the same appSelector with different ports important?

**Comment by bilby91** [comment] 2019-07-19 14:57
Hey @Dean-Coakley I'm glad that you were able to reproduce it!

The multi-deployment with same selector was actually a bug on our end, so, no, we don't need it and we already fixed it! 

What I'm wondering is, shouldn't the ingress controller fail or fail more predictively if that is the case ? I phrased this issue as "I'm not sure this is a bug" since I knew I had something wrong on my end, but still, I thought that a more healthy failure could be added.

Let me know your thoughts!

**Comment by Dean-Coakley** [comment] 2019-07-23 08:28
@bilby91 

> shouldn't the ingress controller fail or fail more predictively if that is the case?

If the deployment emitted an event with the error message, rather than just logging the error on the pods, would that help? - Or do you have something else in mind?

**Comment by bilby91** [comment] 2019-07-24 03:09
@Dean-Coakley Would it be possible to hook into the deployment lifecycle/scheduling and prevent the pod from scheduling  ? I think that would be ideal but I'm not sure if that is even possible :)

**Comment by Dean-Coakley** [comment] 2019-07-26 17:50
I think this would be possible. However, this would mean elevating the privileges of the ingress controller which is something that shouldn't be taken lightly. It's important that the ingress controller stays secure by default.

I think this is also arguably outside the scope of an ingress controller. 
Re: https://kubernetes.io/docs/concepts/services-networking/ingress/#what-is-ingress
> An Ingress controller is responsible for fulfilling the Ingress, usually with a load balancer, though it may also configure your edge router or additional frontends to help handle the traffic.

So the scope of an Ingress Controller is purely to monitor ingress resources and reconfigure backends.

**Comment by bilby91** [comment] 2019-07-26 17:57
@Dean-Coakley That makes sense to me. 

I've been reading a bunch of documentation on how to create controllers so I think I have a better idea now of what is possible.

I was looking to see if the Ingress api supports some kind of status but I can't find what I'm looking for. I was expecting that the Ingress could have some kind `Status: Failed` which would help the user understand that the defined ingress is having issues.

Having said all that, maybe improving the error message would be enough ?

**Comment by Rulox** [comment] 2019-07-29 11:46
Hey @bilby91

I think we can emit an event when this problem happens (warning or error) as @Dean-Coakley suggested. Events are a more "kubernetes" way of reporting problems to the user (https://www.bluematador.com/blog/kubernetes-events-explained).

We already use Events for some errors/warning/information messages. You can see IC events with `kubectl describe pod <YOUR_IC_POD>`.  Alternatively, you can see all the events in your cluster using `kubectl get events`. That way you can see events sent by other resources as well.

For example, the Ingress Controller emits an event for a VirtualServer custom resource when a new VS is added or updated:
```
Events:
  Type    Reason          Age               From                      Message
  ----    ------          ----              ----                      -------
  Normal  Updated         10m               nginx-ingress-controller  Configuration was updated due to updated secret default/cafe-secret
  Normal  Updated         10m               nginx-ingress-controller  Configuration for default/cafe was updated
  Normal  AddedOrUpdated  9m (x2 over 10m)  nginx-ingress-controller  Configuration for default/cafe was added or updated
```

What do you think ? I feel that would be enough for now, and it creates visibility of the issue to the user of the cluster without having to parse logs. Let me know your thoughts and we'll discuss within the team.

**Comment by Dean-Coakley** [comment] 2019-10-22 10:50
Closing. Not a bug. Feel free to reopen if needed.

**Closed by Dean-Coakley** 2019-10-22 10:50 UTC
Labels: bug
